### ISSUE TITLE
Discuss approaches to object-orientation and non-repeated code in PHP APIs

### ISSUE THREAD

**Issue by vkottler** [badgerloop-software/apis#6]

**Comment by jordanjones98** [comment]
What I think we should do is start creating /secure or /admin (whatever we are going to call it) and write that in Laravel. This will help in a couple of ways. One, we can make use of Laravel’s Migrations, and seeds. Then we can write the API behind that and really remove code repetition using Laravels MVC Model (we can talk about how to structure that if we choose this option.)

**Comment by vkottler** [comment]
I think we have a paradigm established
